# Generated by Django 2.2.1 on 2022-08-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedes',
            name='director',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sedes',
            name='foto',
            field=models.FileField(default='', upload_to='fotos/', verbose_name='Foto Sede (476x570)'),
        ),
    ]
