# Generated by Django 2.2.1 on 2022-08-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='evento',
            field=models.BooleanField(default='False'),
        ),
    ]
