# Generated by Django 2.2.1 on 2022-08-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_noticias_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre Cargo')),
            ],
        ),
        migrations.AddField(
            model_name='noticias',
            name='sede',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.Sedes'),
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Primer nombre')),
                ('nombre2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Segundo nombre')),
                ('apellido1', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Segundo apellido')),
                ('foto', models.FileField(default='', upload_to='fotos/', verbose_name='Archivo con Foto del Funcionario')),
                ('direccion', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Dirección Residencia')),
                ('celular', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Número de celular')),
                ('email', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='E-Mail')),
                ('cargo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.Cargos')),
                ('sede', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.Sedes')),
            ],
        ),
    ]
