# Generated by Django 2.2.1 on 2022-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_auto_20220814_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedes',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
