# Generated by Django 2.2.1 on 2022-08-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_sedes_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedes',
            name='ano_fundacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sedes',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sedes',
            name='logo',
            field=models.FileField(default='', upload_to='fotos/', verbose_name='Logo (476x570)'),
        ),
    ]
