# Generated by Django 2.2.1 on 2022-08-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_auto_20220812_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='apellido1',
            field=models.CharField(default='', max_length=50, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='nombre1',
            field=models.CharField(default='', max_length=50, verbose_name='Primer nombre'),
        ),
    ]
