# Generated by Django 2.2.1 on 2022-08-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_auto_20220814_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='foto1',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Foto Sede (800x600)'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='foto2',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Foto Sede (800x600)'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='foto3',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Foto Sede (800x600)'),
        ),
    ]
