# Generated by Django 2.2.1 on 2022-08-17 22:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0009_auto_20220815_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miempresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuestra_empresa', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('mision', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('vision', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('objetivo', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('principios', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nuestra Empresa',
            },
        ),
    ]
