# Generated by Django 2.2.1 on 2022-08-18 00:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0010_miempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='miempresa',
            name='himno_audio',
            field=models.FileField(blank=True, default='', null=True, upload_to='audio/', verbose_name='Archivo Audio Himno Sistema INRAI'),
        ),
        migrations.AddField(
            model_name='miempresa',
            name='himno_letra',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Letra Himno Sistema INRAI'),
        ),
        migrations.AlterField(
            model_name='miempresa',
            name='mision',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Mision'),
        ),
        migrations.AlterField(
            model_name='miempresa',
            name='nuestra_empresa',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Nuestra Empresa'),
        ),
        migrations.AlterField(
            model_name='miempresa',
            name='objetivo',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Objetivo General'),
        ),
        migrations.AlterField(
            model_name='miempresa',
            name='principios',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Principios y Fundamentos'),
        ),
        migrations.AlterField(
            model_name='miempresa',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Vision'),
        ),
    ]
