# Generated by Django 2.2.1 on 2022-08-18 16:45

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0012_bienestar_ocupacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglamento', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Reglamento Interno de Trabajo')),
            ],
            options={
                'verbose_name_plural': 'Reglamento',
            },
        ),
        migrations.AlterModelOptions(
            name='ocupacional',
            options={'verbose_name_plural': 'Salud Ocupacional'},
        ),
        migrations.RemoveField(
            model_name='ocupacional',
            name='reglamento',
        ),
        migrations.AddField(
            model_name='ocupacional',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='ocupacional',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ocupacional',
            name='detalle',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='ocupacional',
            name='foto',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='ocupacional',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ocupacional',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
