# Generated by Django 2.2.1 on 2022-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0014_bienestar_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienestar',
            name='foto',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Foto (417 x 269px)'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='foto',
            field=models.FileField(default='', upload_to='fotos/', verbose_name='Archivo con Foto del Funcionario (200 x 200px)'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen_destacado',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen Destacado (476 x 570px)'),
        ),
        migrations.AlterField(
            model_name='ocupacional',
            name='foto',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Foto (417 x 269px)'),
        ),
    ]
