# Generated by Django 2.2.1 on 2022-08-25 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0015_auto_20220818_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='reglamento',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200000, null=True, verbose_name='Reglamento Interno de Trabajo'),
        ),
    ]
