# Generated by Django 2.2.1 on 2022-08-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0017_reglamento_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generales.Sedes'),
        ),
    ]
