# Generated by Django 2.2.1 on 2022-08-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0020_tipos_tutoriales_tutoriales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriales',
            name='autor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
