# Generated by Django 2.2.1 on 2022-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0021_tutoriales_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipos_tutoriales',
            options={'verbose_name_plural': 'Temas de Tutoriales'},
        ),
        migrations.AlterField(
            model_name='elmuro',
            name='foto',
            field=models.FileField(blank=True, default='', null=True, upload_to='elmuro/', verbose_name='Foto (417 x 269px)'),
        ),
    ]
