# Generated by Django 2.2.1 on 2022-08-30 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0023_elmuro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elmuro',
            name='detalle',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Detalle'),
        ),
    ]
