# Generated by Django 2.2.1 on 2022-09-01 20:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0024_auto_20220830_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuestra_empresa', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Nuestra Empresa')),
                ('comunicaciones', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Mision')),
                ('marketing', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Vision')),
                ('entretenimiento', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True, verbose_name='Objetivo General')),
            ],
            options={
                'verbose_name_plural': 'Pagina principal',
            },
        ),
    ]
