# Generated by Django 2.2.1 on 2022-09-01 21:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0025_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AlterField(
            model_name='home',
            name='comunicaciones',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True, verbose_name='Comunicaciones'),
        ),
        migrations.AlterField(
            model_name='home',
            name='entretenimiento',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True, verbose_name='Entretenimiento'),
        ),
        migrations.AlterField(
            model_name='home',
            name='marketing',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True, verbose_name='Marketing'),
        ),
        migrations.AlterField(
            model_name='home',
            name='nuestra_empresa',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True, verbose_name='Nuestra Empresa'),
        ),
    ]
