# Generated by Django 2.2.1 on 2022-09-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0026_auto_20220901_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Home1',
        ),
    ]
