# Generated by Django 3.2.19 on 2024-02-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0027_auto_20220901_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
