# Generated by Django 3.2.19 on 2024-02-04 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0029_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='fecha_ultimo_carnet',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de ultumo carnet'),
            preserve_default=False,
        ),
    ]
