# Generated by Django 3.2.19 on 2024-02-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0031_alter_funcionarios_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='cedula',
            field=models.CharField(default='', max_length=50, verbose_name='Cedula No. '),
        ),
    ]
