# Generated by Django 3.2.19 on 2024-02-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0033_auto_20240204_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Ausente'), (1, 'En Oficina')], default=0),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='hora_entrada_de_almuerzo',
            field=models.TimeField(blank=True, default='14:00', verbose_name='Hora entrada de almuerzo'),
        ),
        migrations.CreateModel(
            name='io_funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha de nacimiento')),
                ('hora', models.TimeField(blank=True)),
                ('funcionario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.funcionarios')),
            ],
            options={
                'verbose_name_plural': 'IO Funcionarios',
            },
        ),
    ]
