# Generated by Django 3.2.19 on 2024-02-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0034_auto_20240204_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='io_funcionarios',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='io_funcionarios',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='io_funcionarios',
            name='modificado',
        ),
    ]
