# Generated by Django 3.2.19 on 2024-02-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0035_auto_20240205_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='io_funcionarios',
            name='tio_evento',
            field=models.IntegerField(choices=[(0, 'Entra'), (1, 'Sale')], default=0),
        ),
    ]
