# Generated by Django 3.2.19 on 2024-02-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0036_io_funcionarios_tio_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='io_funcionarios',
            old_name='tio_evento',
            new_name='tipo_evento',
        ),
    ]
