# Generated by Django 5.2.8 on 2026-05-13 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0039_migrate_to_ckeditor5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='io_funcionarios',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.funcionarios'),
        ),
    ]
